image: ruby:2.3.0

before_script:
  - gem install bundler --no-ri --no-rdoc
  - bundle install --jobs $(nproc)  "${FLAGS[@]}"

rspec:
  script:
    - ruby -run -e httpd -- -p 4000 spec/fixtures &
    - bundle exec rspec
